[package]
name = "ic-event-hub-macros"
version = "0.1.1"
authors = ["Александр Втюрин <senior.joinu@gmail.com>"]
edition = "2018"
description = "Macroses"
license = "MIT"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
syn = "1.0.73"
quote = "1.0.9"
proc-macro2 = "1.0.27"