[package]
name = "ic-event-hub"
version = "0.1.4"
authors = ["Александр Втюрин <senior.joinu@gmail.com>"]
edition = "2018"
description = "event hub"
license = "MIT"

[dependencies]
ic-cdk = "0.3.1"
serde = "1.0.126"